apiVersion: v1
kind: Pod
metadata:
  name: orca-tester
spec:
  restartPolicy: Never
  containers:
    - name: orca-tester
      image: ghcr.io/cveal-ai-ml/orca:main
      ports:
      - containerPort: 11044
      env:
        - name: NCCL_SOCKET_IFNAME
          value: eth0
        - name: NCCL_DEBUG
          value: INFO
        - name: MASTER_ADDR
          value: localhost
        - name: MASTER_PORT
          value: "11044"
      stdin: True
      tty: True
      resources:
        limits:
          memory: 16G
          cpu: 12
          nvidia.com/gpu: 2
        requests:
          memory: 16G
          cpu: 12
          nvidia.com/gpu: 2
      volumeMounts:
        - name: orca-code
          mountPath: /develop/code
        - name: orca-data
          mountPath: /develop/data
        - name: orca-results
          mountPath: /develop/results
        - name: dshm
          mountPath: /dev/shm

  volumes:
    - name: orca-code
      persistentVolumeClaim:
        claimName: orca-code
    - name: orca-data
      persistentVolumeClaim:
        claimName: orca-data
    - name: orca-results
      persistentVolumeClaim:
        claimName: orca-results
    - name: dshm
      emptyDir:
        medium: Memory
