apiVersion: v1
kind: Pod
metadata:
  name: orca-jupyter
spec:
  restartPolicy: Never
  containers:
    - name: orca-jupyter
      image: ghcr.io/cveal-ai-ml/orca:main
      imagePullPolicy: Always
      # imagePullPolicy: IfNotPresent
      command: ["jupyter", "lab", "--no-browser", "--port=10044"]
      resources:
        limits:
          memory: 16G
          cpu: 16
        requests:
          memory: 16G
          cpu: 16
      volumeMounts:
        - name: orca-code
          mountPath: /develop/code
        - name: orca-data
          mountPath: /develop/data
        - name: orca-results
          mountPath: /develop/results

  volumes:
    - name: orca-code
      persistentVolumeClaim:
        claimName: orca-code
    - name: orca-data
      persistentVolumeClaim:
        claimName: orca-data
    - name: orca-results
      persistentVolumeClaim:
        claimName: orca-results
