# Author: Charlie
# Purpose: DL Autoencoder using lighting AI

# Determine: Experiment
# - experiment: (0) Train DL autoencoder (1) Autoencoder knowledge discovery 

goal:
  experiment: 0

# Create: System Parameters
# - strategy: the parallelization procedure 
# - num_devices: number of dedicated acceleration devices
# - num_workers: number of dataloader processors
# - accelerator: type of acceleration device

system:
  strategy: auto
  num_devices: 2
  num_workers: 7
  accelerator: gpu

# Create: Dataset Parameters
# - transforms: data augmentation strategy
# - interpolate: use data resize transform
# - space_size: number of features for middle of autoencoder
# - sample_size: channels and spatial shape of single sample

datasets:

  transforms: 0
  interpolate: 1

  grayscale: 0
  perecent_class_samples: 1

  space_size: 3
  sample_size: [3, 32, 32]

# Create: Netowrk Parameters
# - batch_size: number of dataset samples per network observation
# - num_epochs: number of times network observes training dataset
# - learning_rate: amount of allowable gradient change in network

network:
  objective: 1
  optimizer: 0
  batch_size: 256
  num_epochs: 1000
  learning_rate: 0.003

# Create: Path Parameters
# - train: path to train folder
# - valid: path to valid folder
# - results: path to results folder

paths:
  train: /develop/data/cifar/train
  valid: /develop/data/cifar/test
  results: /develop/results/cifar/orca
  model: /develop/results/cifar/orca/lightning_logs/training/checkpoints/epoch=99-step=78200.ckpt
